import type { Metadata } from "next";
import AosInit from "./components/AosInit";
import "aos/dist/aos.css";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import About from "./about-us/page";
import Services from "./services/page";
import Contact from "./contact/page";
import Portfolio from "./portfolio/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AosInit />
        <Header />
        {children}
        <About />
        <Portfolio />
        <Services />
        <Contact />
        <Footer/>
      </body>
    </html>
  );
}
